# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

steps:
  # Install Java
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64' # Correct input key
      jdkSourceOption: 'PreInstalled'

  # Run Maven Build
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-DskipTests'

  # Run Tests
  - script: |
      echo "Running tests in headless mode"
      mvn test -Dbrowser=headless
    displayName: 'Run tests'

  # Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      mergeTestResults: true
      testRunTitle: 'Maven Test Results'

  # Publish Code Coverage Results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
      failIfCoverageEmpty: true
