# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  # Install Java JDK 11
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'
      
  # List repository files for debugging purposes
  - script: ls -R /home/vsts/work/1/s
    displayName: 'List repository files'

  # Run Maven build
  - task: Maven@3
    inputs:
      mavenPomFile: 'DemoAutomation_GenAI/my-maven-project/pom.xml' # Adjust path as needed
      goals: 'clean test'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersion: '11'
      jdkArchitecture: 'x64'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
